sylius_resource:
    resources:
        app.author:
            classes:
                model: AppBundle\Entity\Author
                form: AppBundle\Form\Type\AuthorType
            translation:
                classes:
                    model: AppBundle\Entity\AuthorTranslation
                    form: AppBundle\Form\Type\AuthorTranslationType

sylius_grid:
    grids:
        app_admin_author:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Author
            fields:
                images:
                    type: twig
                    label: sylius.ui.image
                    path: .
                    options:
                        template: "@RewindAdmin/Grid/Field/_images.html.twig"
                id:
                    type: string
                    label: sylius.ui.id
                code:
                    type: string
                    label: sylius.ui.code
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    path: .
                    options:
                        template: '@SyliusUi/Grid/Field/enabled.html.twig'
                position:
                    type: twig
                    label: sylius.ui.position
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    book:
                        type: links
                        label: sylius.ui.manage_books
                        options:
                            icon: cubes
                            links:
                                index:
                                    label: sylius.ui.list_books
                                    icon: list
                                    route: app_admin_book_index
                                    parameters:
                                        authorId: resource.id
                                create:
                                    label: sylius.ui.create
                                    icon: plus
                                    route: app_admin_book_create
                                    parameters:
                                        authorId: resource.id